version: 2
jobs:
  build-and-push-image:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add py-pip
            pip install awscli
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" 
            aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" 
            aws configure set aws_session_token "${AWS_SESSION_TOKEN}"

      - run:
          name: Login into ECR and Docker
          command: |
            aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${AWS_ECR_REPO_NAME}"
      - run:
          name: Build and tag Image
          command: |
            docker build -t "${AWS_ECR_IMAGE_NAME}":"${CIRCLE_SHA1}" .
#            docker tag "${AWS_ECR_IMAGE_NAME}":"${AWS_ECR_IMAGE_TAG}"  "${AWS_ECR_REPO_NAME}":"${AWS_ECR_IMAGE_TAG}"
      - run:
          name: Push Image to AWS ECR
          command: |
            docker push "${AWS_ECR_IMAGE_NAME}":"${CIRCLE_SHA1}"
  deploy-to-ecs:
    - run:
        name: Update Task Definition
        command: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "${TASK_DEFINITION_NAME}" --region "${AWS_REGION}")
          NEW_TASK_DEFINTIION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${AWS_ECR_IMAGE_NAME}":"${CIRCLE_SHA1}" '.taskDefinition | .containerDefinitions[0].image = "${AWS_ECR_IMAGE_NAME}":"${CIRCLE_SHA1}" | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)')
          NEW_TASK_INFO=$(aws ecs register-task-definition --region "${AWS_REGION}" --cli-input-json "$NEW_TASK_DEFINTIION")
          NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
    - run:
        name: Update ECS Service with Updated Task Definition
        command: |
          aws ecs update-service --cluster "${CLUSTER_NAME}" --service "${SERVICE_NAME}" --task-definition "${TASK_DEFINITION_NAME}":$NEW_REVISION
 

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build:
    jobs:
    - build-and-push-image:
        filters:
          branches:
            only: 
              - master