version: 2
jobs:
  build-and-push-image:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}" 
            aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" 
            aws configure set aws_session_token "${AWS_SESSION_TOKEN}"
      - run:
          name: Login into ECR and Docker
          command: |
            aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com
      - run:
          name: Build and tag Image
          command: |
            sudo docker build -t "${AWS_ECR_IMAGE_NAME}" .
            sudo docker tag "${AWS_ECR_REPO_NAME}":"${AWS_ECR_IMAGE_TAG}"  "${AWS_ACCOUNT_ID}".dkr.ecr."{AWS_REGION}".amazonaws.com/"${AWS_ECR_REPO_NAME}":"${AWS_ECR_IMAGE_TAG}"
      - run:
          name: Push Image to AWS ECR
          command: |
            docker push "${AWS_ACCOUNT_ID}".dkr.ecr."{AWS_REGION}".amazonaws.com/"${AWS_ECR_REPO_NAME}":"${AWS_ECR_IMAGE_TAG}"



# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build:
    jobs:
    - build-and-push-image:
        filters:
          branches:
            only: 
              - master